name: Merge Dev to Prod (With Approval)

on:
  pull_request:
    branches:
      - prod
    types:
      - closed  # Runs only when a PR to 'prod' is closed (merged)

jobs:
  merge_dev_to_prod:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git Credentials
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Authenticate with PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/charles-ja/Dream-Journal-SWE.git

      - name: Merge dev into prod
        run: |
          git fetch origin
          git checkout prod
          git merge --no-ff dev -m "Auto-merge dev into prod after PR approval"
          git push origin prod


